import { defineConfig, loadEnv } from 'vite'
import vue from '@vitejs/plugin-vue'
import tailwindcss from '@tailwindcss/vite'
import path from 'path'
import fs from 'fs'

// https://vitejs.dev/config/
export default defineConfig(({ mode }) => {
  // Load env file based on mode
  const env = loadEnv(mode, process.cwd(), '')
  
  // Plugin to write PHP config file with env values
  function phpEnvPlugin() {
    return {
      name: 'php-env',
      closeBundle() {
        const baseUrl = env.VITE_BASE_URL || 'https://app.proleadsai.com'
        const apiMode = env.VITE_API_MODE || 'prod'
        
        const phpConfig = `<?php
// Auto-generated by Vite build - DO NOT EDIT
// Generated: ${new Date().toISOString()}
// Mode: ${apiMode}

if (!defined('ABSPATH')) exit;

define('PROLEADSAI_BASE_URL', '${baseUrl}');
define('PROLEADSAI_API_MODE', '${apiMode}');
`
        fs.writeFileSync(
          path.resolve(process.cwd(), 'includes/build-config.php'),
          phpConfig
        )
        console.log(`\n📝 Generated includes/build-config.php (${apiMode} mode)`)
      }
    }
  }

  return {
    plugins: [vue(), tailwindcss(), phpEnvPlugin()],
  build: {
    outDir: 'admin/dist',
    emptyOutDir: true,
    rollupOptions: {
      input: 'admin/src/main.js',
      output: {
        entryFileNames: 'proleadsai-admin.js',
        assetFileNames: 'proleadsai-admin.[ext]'
      }
    }
  },
  resolve: {
    alias: {
      '@': path.resolve(process.cwd(), './admin/src')
    }
  }
  }
})
