<?php
/**
 * AJAX handlers for onboarding
 */

if (!defined('ABSPATH')) {
    exit;
}

// Load build-time config (generated by Vite)
$proleadsai_build_config = dirname(__DIR__) . '/build-config.php';
if (file_exists($proleadsai_build_config)) {
    require_once $proleadsai_build_config;
}

/**
 * Get the base URL (without /api suffix)
 * Uses build-config.php generated by Vite, or falls back to production
 */
function proleadsai_get_base_url() {
    // Use build-time constant from Vite (includes/build-config.php)
    if (defined('PROLEADSAI_BASE_URL')) {
        return PROLEADSAI_BASE_URL;
    }
    
    // Fallback to production
    return 'https://app.proleadsai.com';
}

/**
 * Get the API URL (base URL + /api)
 */
function proleadsai_get_api_url() {
    return proleadsai_get_base_url() . '/api';
}

/**
 * Helper function to make API requests with proper SSL handling
 * Handles SSL compatibility issues with older PHP/OpenSSL versions
 */
function proleadsai_api_request($url, $args = array()) {
    $defaults = array(
        'timeout' => 30,
        'sslverify' => true,
        'headers' => array('Content-Type' => 'application/json'),
    );
    
    $args = wp_parse_args($args, $defaults);
    
    return wp_remote_request($url, $args);
}

/**
 * Verify nonce and capability for AJAX requests
 */
function proleadsai_verify_ajax_request() {
    // Check nonce from header or POST data
    $nonce = isset($_SERVER['HTTP_X_WP_NONCE']) ? sanitize_text_field(wp_unslash($_SERVER['HTTP_X_WP_NONCE'])) : '';
    if (empty($nonce)) {
        $json = file_get_contents('php://input');
        $data = json_decode($json, true);
        $nonce = $data['_wpnonce'] ?? '';
    }
    
    if (!wp_verify_nonce($nonce, 'wp_rest')) {
        wp_send_json_error(array('message' => 'Security check failed'), 403);
        exit;
    }
    
    // Check user capability
    if (!current_user_can('manage_options')) {
        wp_send_json_error(array('message' => 'Permission denied'), 403);
        exit;
    }
}

/**
 * Send verification email (OTP)
 */
function proleadsai_send_verification_email() {
    proleadsai_verify_ajax_request();
    
    $json = file_get_contents('php://input');
    $data = json_decode($json, true);
    
    $email = sanitize_email($data['email'] ?? '');
    
    if (empty($email)) {
        wp_send_json_error(array('message' => 'Email is required'));
        return;
    }
    
    $api_url = proleadsai_get_api_url();
    
    $response = proleadsai_api_request($api_url . '/wordpress/auth/register', array(
        'method' => 'POST',
        'body' => json_encode(array('email' => $email))
    ));
    
    if (is_wp_error($response)) {
        wp_send_json_error(array('message' => $response->get_error_message()));
        return;
    }
    
    $status_code = wp_remote_retrieve_response_code($response);
    $body = wp_remote_retrieve_body($response);
    $result = json_decode($body, true);
    
    if ($status_code >= 400) {
        wp_send_json_error(array('message' => $result['message'] ?? 'Failed to send verification email'));
        return;
    }
    
    wp_send_json_success($result);
}
add_action('wp_ajax_proleadsai_send_verification_email', 'proleadsai_send_verification_email');

/**
 * Verify OTP code
 */
function proleadsai_verify_otp() {
    proleadsai_verify_ajax_request();
    
    $json = file_get_contents('php://input');
    $data = json_decode($json, true);
    
    $email = sanitize_email($data['email'] ?? '');
    $code = sanitize_text_field($data['code'] ?? '');
    
    if (empty($email) || empty($code)) {
        wp_send_json_error(array('message' => 'Email and code are required'));
        return;
    }
    
    $api_url = proleadsai_get_api_url();
    
    $response = proleadsai_api_request($api_url . '/wordpress/auth/verify-otp', array(
        'method' => 'POST',
        'body' => json_encode(array('email' => $email, 'code' => $code))
    ));
    
    if (is_wp_error($response)) {
        wp_send_json_error(array('message' => $response->get_error_message()));
        return;
    }
    
    $status_code = wp_remote_retrieve_response_code($response);
    $body = wp_remote_retrieve_body($response);
    $result = json_decode($body, true);
    
    if ($status_code >= 400) {
        wp_send_json_error(array('message' => $result['message'] ?? 'Verification failed'));
        return;
    }
    
    wp_send_json_success($result);
}
add_action('wp_ajax_proleadsai_verify_otp', 'proleadsai_verify_otp');

/**
 * Create business - creates org + API key
 */
function proleadsai_create_business() {
    proleadsai_verify_ajax_request();
    
    $json = file_get_contents('php://input');
    $data = json_decode($json, true);
    
    $user_id = sanitize_text_field($data['userId'] ?? '');
    $business_name = sanitize_text_field($data['businessName'] ?? '');
    
    if (empty($user_id) || empty($business_name)) {
        wp_send_json_error(array('message' => 'userId and businessName are required'));
        return;
    }
    
    $api_url = proleadsai_get_api_url();
    
    $response = proleadsai_api_request($api_url . '/wordpress/auth/create-business', array(
        'method' => 'POST',
        'body' => json_encode(array(
            'userId' => $user_id,
            'businessName' => $business_name,
            'siteUrl' => get_site_url()
        ))
    ));
    
    if (is_wp_error($response)) {
        wp_send_json_error(array('message' => $response->get_error_message()));
        return;
    }
    
    $status_code = wp_remote_retrieve_response_code($response);
    $body = wp_remote_retrieve_body($response);
    $result = json_decode($body, true);
    
    if ($status_code >= 400) {
        wp_send_json_error(array('message' => $result['message'] ?? 'Failed to create business'));
        return;
    }
    
    wp_send_json_success($result);
}
add_action('wp_ajax_proleadsai_create_business', 'proleadsai_create_business');

/**
 * Update organization settings (Google Maps API key, price per sq ft)
 */
function proleadsai_update_settings() {
    proleadsai_verify_ajax_request();
    
    $json = file_get_contents('php://input');
    $data = json_decode($json, true);
    
    $user_id = sanitize_text_field($data['userId'] ?? '');
    
    if (empty($user_id)) {
        wp_send_json_error(array('message' => 'userId is required'));
        return;
    }
    
    $api_url = proleadsai_get_api_url();
    
    $body = array('userId' => $user_id);
    
    if (isset($data['businessName'])) {
        $body['businessName'] = sanitize_text_field($data['businessName']);
    }
    
    if (isset($data['googleMapsApiKey'])) {
        $body['googleMapsApiKey'] = sanitize_text_field($data['googleMapsApiKey']);
    }

    if (isset($data['googleSolarApiKey'])) {
        $body['googleSolarApiKey'] = sanitize_text_field($data['googleSolarApiKey']);
    }
    
    if (isset($data['pricePerSq'])) {
        $body['pricePerSq'] = intval($data['pricePerSq']);
    }
    
    if (isset($data['timezone'])) {
        $body['timezone'] = sanitize_text_field($data['timezone']);
    }
    
    $response = proleadsai_api_request($api_url . '/wordpress/auth/update-settings', array(
        'method' => 'POST',
        'body' => json_encode($body)
    ));
    
    if (is_wp_error($response)) {
        wp_send_json_error(array('message' => $response->get_error_message()));
        return;
    }
    
    $status_code = wp_remote_retrieve_response_code($response);
    $response_body = wp_remote_retrieve_body($response);
    $result = json_decode($response_body, true);
    
    if ($status_code >= 400) {
        wp_send_json_error(array('message' => $result['message'] ?? 'Failed to update settings'));
        return;
    }
    
    wp_send_json_success($result);
}
add_action('wp_ajax_proleadsai_update_settings', 'proleadsai_update_settings');

/**
 * Get user's existing WordPress organization
 */
function proleadsai_get_user_org() {
    proleadsai_verify_ajax_request();
    
    $json = file_get_contents('php://input');
    $data = json_decode($json, true);
    
    $user_id = sanitize_text_field($data['userId'] ?? '');
    
    if (empty($user_id)) {
        wp_send_json_error(array('message' => 'userId is required'));
        return;
    }
    
    $api_url = proleadsai_get_api_url();
    
    $response = proleadsai_api_request($api_url . '/wordpress/auth/user-org?userId=' . urlencode($user_id), array(
        'method' => 'GET'
    ));
    
    if (is_wp_error($response)) {
        wp_send_json_error(array('message' => $response->get_error_message()));
        return;
    }
    
    $status_code = wp_remote_retrieve_response_code($response);
    $body = wp_remote_retrieve_body($response);
    $result = json_decode($body, true);
    
    if ($status_code >= 400) {
        wp_send_json_error(array('message' => $result['message'] ?? 'Failed to fetch user organization'));
        return;
    }
    
    wp_send_json_success($result);
}
add_action('wp_ajax_proleadsai_get_user_org', 'proleadsai_get_user_org');

/**
 * Save onboarding state locally
 */
function proleadsai_onboarding_save() {
    proleadsai_verify_ajax_request();
    
    $json = file_get_contents('php://input');
    $data = json_decode($json, true);
    
    if (!empty($data) && is_array($data)) {
        // Sanitize each field
        $sanitized = array();
        // Fields that can contain emojis (don't use sanitize_text_field which strips them)
        $emoji_fields = array('button_emoji');
        
        foreach ($data as $key => $value) {
            $key = sanitize_key($key);
            if (is_string($value)) {
                if (in_array($key, $emoji_fields)) {
                    // For emoji fields, just trim and limit length
                    $sanitized[$key] = mb_substr(trim($value), 0, 10);
                } else {
                    $sanitized[$key] = sanitize_text_field($value);
                }
            } elseif (is_bool($value)) {
                $sanitized[$key] = (bool) $value;
            } elseif (is_int($value)) {
                $sanitized[$key] = intval($value);
            } elseif (is_array($value)) {
                // For nested arrays, sanitize recursively
                $sanitized[$key] = array_map('sanitize_text_field', $value);
            }
        }
        
        $current = get_option('proleadsai_onboarding', array());
        $updated = array_merge($current, $sanitized);
        update_option('proleadsai_onboarding', $updated);
    }
    
    wp_send_json_success();
}
add_action('wp_ajax_proleadsai_onboarding_save', 'proleadsai_onboarding_save');

/**
 * Get onboarding state
 */
function proleadsai_onboarding_get() {
    proleadsai_verify_ajax_request();
    
    $data = get_option('proleadsai_onboarding', array());
    wp_send_json($data);
}
add_action('wp_ajax_proleadsai_onboarding_get', 'proleadsai_onboarding_get');

/**
 * Update organization settings
 */
function proleadsai_update_organization() {
    proleadsai_verify_ajax_request();
    
    $json = file_get_contents('php://input');
    $data = json_decode($json, true);
    
    $team_id = sanitize_text_field($data['team_id'] ?? '');
    $auth_token = sanitize_text_field($data['auth_token'] ?? '');
    
    if (empty($team_id) || empty($auth_token)) {
        wp_send_json_error(array('message' => 'Missing credentials'));
        return;
    }
    
    $api_url = proleadsai_get_api_url();
    
    $response = proleadsai_api_request($api_url . '/organization/' . $team_id . '/settings', array(
        'method' => 'PATCH',
        'headers' => array(
            'Content-Type' => 'application/json',
            'x-api-key' => $auth_token
        ),
        'body' => json_encode(array(
            'name' => sanitize_text_field($data['name'] ?? ''),
            'googleMapsApiKey' => sanitize_text_field($data['googleMapsApiKey'] ?? ''),
            'pricePerSq' => intval($data['pricePerSq'] ?? 750)
        ))
    ));
    
    if (is_wp_error($response)) {
        wp_send_json_error(array('message' => $response->get_error_message()));
        return;
    }
    
    $body = wp_remote_retrieve_body($response);
    $result = json_decode($body, true);
    
    wp_send_json_success($result);
}
add_action('wp_ajax_proleadsai_update_organization', 'proleadsai_update_organization');

/**
 * Validate Google Maps API Key
 * Tests Places Autocomplete and Solar API directly from WordPress server
 * This ensures the API key works with the domain restrictions set by the user
 */
function proleadsai_validate_api_key() {
    proleadsai_verify_ajax_request();
    
    $json = file_get_contents('php://input');
    $data = json_decode($json, true);
    
    $api_key = sanitize_text_field($data['apiKey'] ?? $data['placesApiKey'] ?? '');
    $wp_base_url = sanitize_text_field($data['wpBaseUrl'] ?? '');
    
    if (empty($api_key)) {
        wp_send_json_error(array('message' => 'API key is required'));
        return;
    }

    if (empty($wp_base_url)) {
        $wp_base_url = get_site_url();
    }

    $base_url = function_exists('proleadsai_get_base_url') ? proleadsai_get_base_url() : 'https://app.proleadsai.com';
    $endpoint = rtrim($base_url, '/') . '/api/wordpress/auth/validate-maps-key';

    $response = proleadsai_api_request($endpoint, array(
        'method' => 'POST',
        'headers' => array('Content-Type' => 'application/json'),
        'body' => wp_json_encode(array(
            'apiKey' => $api_key,
            'wpBaseUrl' => $wp_base_url,
        )),
        'timeout' => 20,
    ));

    if (is_wp_error($response)) {
        wp_send_json_error(array('message' => $response->get_error_message()));
        return;
    }

    $status_code = wp_remote_retrieve_response_code($response);
    $body = wp_remote_retrieve_body($response);
    $decoded = json_decode($body, true);

    if ($status_code >= 400) {
        wp_send_json_error(array('message' => $decoded['message'] ?? 'Failed to validate API key'));
        return;
    }

    $results = $decoded['results'] ?? array();

    // Determine overall success based on Places API validation
    $success = true;
    foreach ($results as $host => $checks) {
        if (empty($checks['placesApi']['valid'])) {
            $success = false;
            break;
        }
    }

    wp_send_json_success(array(
        'success' => $success,
        'results' => $results,
    ));
}
add_action('wp_ajax_proleadsai_validate_api_key', 'proleadsai_validate_api_key');

/**
 * Validate Google Solar API Key via backend
 * This tests the Solar API server-side since it doesn't have referrer restrictions
 */
function proleadsai_validate_solar_api() {
    proleadsai_verify_ajax_request();
    
    $json = file_get_contents('php://input');
    $data = json_decode($json, true);
    
    $api_key = sanitize_text_field($data['apiKey'] ?? '');
    
    if (empty($api_key)) {
        wp_send_json_error(array('message' => 'API key is required'));
        return;
    }

    $base_url = function_exists('proleadsai_get_base_url') ? proleadsai_get_base_url() : 'https://app.proleadsai.com';
    $endpoint = rtrim($base_url, '/') . '/api/wordpress/auth/validate-maps-key';

    $response = proleadsai_api_request($endpoint, array(
        'method' => 'POST',
        'headers' => array('Content-Type' => 'application/json'),
        'body' => wp_json_encode(array(
            'apiKey' => $api_key,
        )),
        'timeout' => 20,
    ));

    if (is_wp_error($response)) {
        wp_send_json_error(array('message' => $response->get_error_message()));
        return;
    }

    $status_code = wp_remote_retrieve_response_code($response);
    $body = wp_remote_retrieve_body($response);
    $decoded = json_decode($body, true);

    if ($status_code >= 400) {
        wp_send_json_error(array('message' => $decoded['message'] ?? 'Failed to validate Solar API'));
        return;
    }

    wp_send_json_success(array(
        'success' => $decoded['success'] ?? false,
        'solarApi' => $decoded['solarApi'] ?? array('valid' => false, 'message' => 'Unknown error'),
    ));
}
add_action('wp_ajax_proleadsai_validate_solar_api', 'proleadsai_validate_solar_api');

/**
 * Reset all plugin data (for testing)
 */
function proleadsai_reset_data() {
    proleadsai_verify_ajax_request();
    
    delete_option('proleadsai_onboarding');
    delete_option('proleadsai_dev_api_url');
    wp_send_json_success(array('message' => 'All plugin data has been reset'));
}
add_action('wp_ajax_proleadsai_reset_data', 'proleadsai_reset_data');

/**
 * Set dev API URL (for local development)
 */
function proleadsai_set_dev_api_url() {
    proleadsai_verify_ajax_request();
    
    $json = file_get_contents('php://input');
    $data = json_decode($json, true);
    
    $url = esc_url_raw($data['url'] ?? '');
    
    if (empty($url)) {
        delete_option('proleadsai_dev_api_url');
        wp_send_json_success(array('message' => 'Dev API URL cleared, using production'));
        return;
    }
    
    update_option('proleadsai_dev_api_url', $url);
    wp_send_json_success(array('message' => 'Dev API URL set to: ' . $url));
}
add_action('wp_ajax_proleadsai_set_dev_api_url', 'proleadsai_set_dev_api_url');

/**
 * Proxy: Get settings from Better Auth API
 */
function proleadsai_proxy_get_settings() {
    proleadsai_verify_ajax_request();
    
    $settings = get_option('proleadsai_onboarding', array());
    $auth_token = $settings['auth_token'] ?? '';
    
    if (empty($auth_token)) {
        wp_send_json_error(array('message' => 'Not authenticated'));
        return;
    }
    
    $api_url = proleadsai_get_api_url();
    
    $response = proleadsai_api_request($api_url . '/wordpress/settings', array(
        'method' => 'GET',
        'headers' => array(
            'Content-Type' => 'application/json',
            'x-api-key' => $auth_token,
            'Accept' => 'application/json'
        )
    ));
    
    if (is_wp_error($response)) {
        wp_send_json_error(array('message' => $response->get_error_message()));
        return;
    }
    
    $status_code = wp_remote_retrieve_response_code($response);
    $body = wp_remote_retrieve_body($response);
    $data = json_decode($body, true);
    
    if ($status_code >= 400) {
        wp_send_json_error(array('message' => $data['message'] ?? 'Failed to fetch settings'));
        return;
    }
    
    // Sync API data back to WordPress
    if ($data) {
        $updates = array();
        if (!empty($data['name'])) $updates['business'] = $data['name'];
        if (!empty($data['email'])) $updates['email'] = $data['email'];
        if (isset($data['googleMapsApiKey'])) $updates['google_maps_api_key'] = $data['googleMapsApiKey'];
        if (isset($data['googleSolarApiKey'])) $updates['google_solar_api_key'] = $data['googleSolarApiKey'];
        if (isset($data['pricePerSq'])) $updates['price_per_sq'] = strval($data['pricePerSq']);
        if (!empty($data['timezone'])) $updates['timezone'] = $data['timezone'];
        if (!empty($data['id'])) $updates['team_id'] = $data['id'];
        
        if (!empty($updates)) {
            $current = get_option('proleadsai_onboarding', array());
            update_option('proleadsai_onboarding', array_merge($current, $updates));
        }
    }
    
    wp_send_json_success($data);
}
add_action('wp_ajax_proleadsai_proxy_get_settings', 'proleadsai_proxy_get_settings');

/**
 * Proxy: Get dashboard data from Better Auth API
 */
function proleadsai_proxy_get_dashboard() {
    proleadsai_verify_ajax_request();
    
    $settings = get_option('proleadsai_onboarding', array());
    $auth_token = $settings['auth_token'] ?? '';
    
    if (empty($auth_token)) {
        wp_send_json_error(array('message' => 'Not authenticated'));
        return;
    }
    
    $api_url = proleadsai_get_api_url();
    
    // Verify nonce for GET parameter processing (check header first, then request data)
    $nonce = '';
    if (isset($_SERVER['HTTP_X_WP_NONCE'])) {
        $nonce = sanitize_text_field(wp_unslash($_SERVER['HTTP_X_WP_NONCE']));
    } elseif (isset($_REQUEST['_wpnonce'])) {
        $nonce = sanitize_text_field(wp_unslash($_REQUEST['_wpnonce']));
    }
    
    if (empty($nonce) || !wp_verify_nonce($nonce, 'wp_rest')) {
        wp_send_json_error(array('message' => 'Security check failed'), 403);
        return;
    }
    
    // Forward date range params if provided
    $query_params = array();
    if (!empty($_GET['startDate'])) {
        $query_params['startDate'] = sanitize_text_field(wp_unslash($_GET['startDate']));
    }
    if (!empty($_GET['endDate'])) {
        $query_params['endDate'] = sanitize_text_field(wp_unslash($_GET['endDate']));
    }
    
    $url = $api_url . '/wordpress/dashboard';
    if (!empty($query_params)) {
        $url .= '?' . http_build_query($query_params);
    }
    
    $response = proleadsai_api_request($url, array(
        'method' => 'GET',
        'headers' => array(
            'Content-Type' => 'application/json',
            'x-api-key' => $auth_token,
            'Accept' => 'application/json'
        )
    ));
    
    if (is_wp_error($response)) {
        wp_send_json_error(array('message' => $response->get_error_message()));
        return;
    }
    
    $status_code = wp_remote_retrieve_response_code($response);
    $body = wp_remote_retrieve_body($response);
    $data = json_decode($body, true);
    
    if ($status_code >= 400) {
        wp_send_json_error(array('message' => $data['message'] ?? 'Failed to fetch dashboard data'));
        return;
    }
    
    wp_send_json_success($data);
}
add_action('wp_ajax_proleadsai_proxy_get_dashboard', 'proleadsai_proxy_get_dashboard');

/**
 * Proxy: Save settings to Better Auth API
 */
function proleadsai_proxy_save_settings() {
    proleadsai_verify_ajax_request();
    
    $settings = get_option('proleadsai_onboarding', array());
    $auth_token = $settings['auth_token'] ?? '';
    
    if (empty($auth_token)) {
        wp_send_json_error(array('message' => 'Not authenticated'));
        return;
    }
    
    $json = file_get_contents('php://input');
    $data = json_decode($json, true);
    
    $api_url = proleadsai_get_api_url();
    
    $body = array();
    if (isset($data['name'])) $body['name'] = sanitize_text_field($data['name']);
    if (isset($data['googleMapsApiKey'])) $body['googleMapsApiKey'] = sanitize_text_field($data['googleMapsApiKey']);
    if (isset($data['googleSolarApiKey'])) $body['googleSolarApiKey'] = sanitize_text_field($data['googleSolarApiKey']);
    if (isset($data['pricePerSq'])) $body['pricePerSq'] = intval($data['pricePerSq']);
    if (isset($data['timezone'])) $body['timezone'] = sanitize_text_field($data['timezone']);
    
    $response = proleadsai_api_request($api_url . '/wordpress/settings', array(
        'method' => 'POST',
        'headers' => array(
            'Content-Type' => 'application/json',
            'x-api-key' => $auth_token,
            'Accept' => 'application/json'
        ),
        'body' => json_encode($body)
    ));
    
    if (is_wp_error($response)) {
        wp_send_json_error(array('message' => $response->get_error_message()));
        return;
    }
    
    $status_code = wp_remote_retrieve_response_code($response);
    $response_body = wp_remote_retrieve_body($response);
    $result = json_decode($response_body, true);
    
    if ($status_code >= 400) {
        wp_send_json_error(array('message' => $result['message'] ?? 'Failed to save settings'));
        return;
    }
    
    // Sync to WordPress after successful API save
    $updates = array();
    if (isset($data['name'])) $updates['business'] = $data['name'];
    if (isset($data['googleMapsApiKey'])) $updates['google_maps_api_key'] = $data['googleMapsApiKey'];
    if (isset($data['googleSolarApiKey'])) $updates['google_solar_api_key'] = $data['googleSolarApiKey'];
    if (isset($data['pricePerSq'])) $updates['price_per_sq'] = strval($data['pricePerSq']);
    if (isset($data['timezone'])) $updates['timezone'] = $data['timezone'];
    
    if (!empty($updates)) {
        $current = get_option('proleadsai_onboarding', array());
        update_option('proleadsai_onboarding', array_merge($current, $updates));
    }
    
    wp_send_json_success($result);
}
add_action('wp_ajax_proleadsai_proxy_save_settings', 'proleadsai_proxy_save_settings');
