export { default as StepWelcome } from './StepWelcome.vue'
export { default as StepEmail } from './StepEmail.vue'
export { default as StepBusiness } from './StepBusiness.vue'
export { default as StepGoogleMaps } from './StepGoogleMaps.vue'
export { default as StepGoogleSolar } from './StepGoogleSolar.vue'
export { default as StepTheme } from './StepTheme.vue'
export { default as ApiFixModal } from './ApiFixModal.vue'
