<?php
// Auto-generated by Vite build - DO NOT EDIT
// Generated: 2025-12-06T00:18:13.863Z
// Mode: dev

if (!defined('ABSPATH')) exit;

define('PROLEADSAI_BASE_URL', 'http://0.0.0.0:3000');
define('PROLEADSAI_API_MODE', 'dev');
