<?php
// Auto-generated by Vite build - DO NOT EDIT
// Generated: 2026-02-11T01:37:23.997Z
// Mode: prod

if (!defined('ABSPATH')) exit;

define('PROLEADSAI_BASE_URL', 'https://app.proleadsai.com');
define('PROLEADSAI_API_MODE', 'prod');
